### ISSUE TITLE
Still unable to access

### ISSUE THREAD

**Issue by woody544** [dorisavedikian/NALGuideToSubjectIndexing#10]
@dorisavedikian FYSA I have been trying periodically to access the book, with no luck!

**Comment by dorisavedikian** [comment]
> @dorisavedikian FYSA I have been trying periodically to access the book, with no luck!

Ok its fixed! [Link to site](https://dorisavedikian.github.io/NALGuideToSubjectIndexing/)

Updating the python version to 3.11.1 and the version for Git Hub actions "actions-gh-pages" to its latest versions fixed it.

**Comment by woody544** [comment]
@dorisavedikian FANTASTIC!!
