### ISSUE TITLE
Add supplements to Indexing Guidelines

### ISSUE THREAD

**Issue by TaMcG412** [dorisavedikian/NALGuideToSubjectIndexing#4]
Please add Supplements A & B to book. Will send Resources list tomorrow. 

[6_Draft Supplement A_articles not indexed_03March2023.docx](https://github.com/dorisavedikian/NALGuideToSubjectIndexing/files/10935823/6_Draft.Supplement.A_articles.not.indexed_03March2023.docx)

[7_Draft Supplement B_additional resources_03March2023.docx](https://github.com/dorisavedikian/NALGuideToSubjectIndexing/files/10935831/7_Draft.Supplement.B_additional.resources_03March2023.docx)

**Comment by dorisavedikian** [comment]
@TaMcG412 I do not have access to the 'CSE Abstracts Error List' in Supp. A. Can you please send that to me?

**Comment by TaMcG412** [comment]
It's a folder in our Teams channel so I am not sure what is the best way for you to be able to add this. I'll provide a folder with the individual files in it but the contents are dynamic so those contents will change.

The link we can use internally is: https://usdagcc.sharepoint.com/:f:/s/ars-nal-dpd-DPD-IIB-GuidelinesandReferences/EpkNUx1jaRlAqqEyQtI14D0BvMyzUb0_sC6XJ-Q9Svnycg?e=Q4wrCV.

[OneDrive_2023-03-13.zip](https://github.com/dorisavedikian/NALGuideToSubjectIndexing/files/10956896/OneDrive_2023-03-13.zip)


This is something we can discuss at the next meeting - how best to add links to internal resources that you may not be able to access.

**Comment by dorisavedikian** [comment]
@TaMcG412 OK I think the best thing to do is to just have the link above available.
