### ISSUE TITLE
Add resources supplement

### ISSUE THREAD

**Issue by TaMcG412** [dorisavedikian/NALGuideToSubjectIndexing#5]
I've attached the Resources supplement as well as a zip file with the individual articles. Hopefully the article names are clear enough that you can match them up.

[12_Draft Resources_03March2023.docx](https://github.com/dorisavedikian/NALGuideToSubjectIndexing/files/10942991/12_Draft.Resources_03March2023.docx)

[Resources full text articles.zip](https://github.com/dorisavedikian/NALGuideToSubjectIndexing/files/10943016/Resources.full.text.articles.zip)

**Comment by dorisavedikian** [comment]
@TaMcG412 Do you have a pdf of this article: Bonnichon, M. (1994). Guide to indexing for AGRIS and CARIS. Rome: FAO.? 

I can't find one available online and I don't see this one in the zip folder you sent.

**Comment by TaMcG412** [comment]
This is one that I have not been able to find anywhere (i.e., no hard copy in any library, no links, no websites). All I have is the citation - we may just have to go with that for now (unless someone has a copy secreted away in a personal collection).

**Comment by TaMcG412** [comment]
I've attached a text tile with the Teams links - let me know if that works better than using the full-text documents. 

[Indexing Guidelines_Resources links in Teams.txt](https://github.com/dorisavedikian/NALGuideToSubjectIndexing/files/10984253/Indexing.Guidelines_Resources.links.in.Teams.txt)

**Comment by TaMcG412** [comment]
There is one other option for the Bonnichon citation. It is a website that appears to be related to that guide but was created by someone else a few years after the guide was published.

https://www.fao.org/3/u1808e/U1808E00.htm#TopOfPage
