### ISSUE TITLE
Add screenshot to guidelines

### ISSUE THREAD

**Issue by TaMcG412** [dorisavedikian/NALGuideToSubjectIndexing#8]
Please add "Scientific Names OR Common Names I_20220731" screenshot and text to annotation in Subject Analysis/Taxonomic Names section. 

[Scientific Names OR Common Names I_20220731.docx](https://github.com/dorisavedikian/NALGuideToSubjectIndexing/files/11190578/Scientific.Names.OR.Common.Names.I_20220731.docx)

**Comment by dorisavedikian** [comment]
All done.
